---
- name: Fedora Setup
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: tasks/setup-packages.yml
    # - import_tasks: tasks/install_neovim.yml
    # - import_tasks: tasks/setup-ssh.yml
    - import_tasks: tasks/dotfiles.yml
    # - import_tasks: tasks/setup-sway-i3.yml
    # - import_tasks: tasks/setup-keyboard.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/misc.yml
  handlers:
    - import_tasks: handlers/main.yml




