---
- name: Setup Git config
  ansible.builtin.file:
    src: "/home/tzen/.dotfiles/Git/.gitconfig"
    dest: "/home/tzen/.gitconfig"
    state: link

- name: Setup Git Ignore_global
  ansible.builtin.file:
    src: "/home/tzen/.dotfiles/Git/.gitignore_global"
    dest: "/home/tzen/.gitignore_global"
    state: link

- name: SymLink Neovim
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link

- name: make sure i3 folder exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/i3/"
    state: directory

- name: Symlink i3 Config
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/i3/config"
    dest: "{{ lookup('env', 'HOME') }}/.config/i3/config"
    state: link
  when: lookup('ansible.builtin.env', 'XDG_SESSION_TYPE') == 'x11'

- name: make sure sway folder exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/sway/"
    state: directory

- name: Symlink wayland Config
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/sway/config"
    dest: "{{ lookup('env', 'HOME') }}/.config/sway/config"
    state: link
  when: lookup('ansible.builtin.env', 'XDG_SESSION_TYPE') == 'wayland'


# - name: make sure zsh folder exist
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/.config/zsh/"
#     state: directory

- name: Symlink my zshrc to home
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/zsh/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link

