---
- name: Setup Git config
  ansible.builtin.file:
    src: "/home/tzen/.dotfiles/Git/.gitconfig"
    dest: "/home/tzen/.gitconfig"
    state: link

- name: Setup Git Ignore_global
  ansible.builtin.file:
    src: "/home/tzen/.dotfiles/Git/.gitignore_global"
    dest: "/home/tzen/.gitignore_global"
    state: link

