---
- name: Compile and install Neovim from source
  block:
    - name: Clone Neovim repo
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/repo/neovim"
        clone: yes
        update: yes

    - name: Build Neovim
      ansible.builtin.shell: |
        cd $HOME/repo/neovim
        make CMAKE_BUILD_TYPE=RelWithDebInfo
      args:
        creates: "{{ lookup('env', 'HOME') }}/repo/neovim/build/bin/nvim"

    - name: Install Neovim
      ansible.builtin.shell: |
        cd $HOME/repo/neovim
        make install
      args:
        creates: "/usr/local/bin/nvim"

