---
- name: Make sure Throw-away-code dir exist
  file:
    path: "{{ lookup('env', 'HOME') }}/throw-away-code" 
    state: directory

- name: Make sure repo dir exist
  file:
    path: "{{ lookup('env', 'HOME') }}/repo" 
    state: directory

- name: Make sure the mnt dir exist in home
  file:
    path: "{{ lookup('env', 'HOME') }}/mnt"
    state: directory
