---
- name: Update all packages to the latest version
  become: yes
  package:
    name: "*"
    state: latest

# Flatpak and Discord
# - name: Install Flatpak 
#   become: yes
#   package:
#     name: flatpak
#     state: latest
# Flatpak is installed by default

- name: Add the Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flathub Packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flathub_packages }}"

- name: Install flathub Packages that runs on only x86
  community.general.flatpak:
    name: "{{ flathub_packages_x86 }}"
    state: present
    remote: flathub
  when: ansible_architecture == "x86_64"

- name: Install required packages
  become: yes
  package:
    name: "{{ packages }}"
    state: latest

- name: Install required packages when on x86
  become: yes
  package:
    name: "{{ packages_x86 }}"
    state: latest
  when: ansible_architecture == "x86_64"

- name: Install Neovim dependencies
  become: yes
  package:
    name: "{{ neovim_dependencies }}"
    state: latest

- name: Enable Wezterm in Copr
  become: yes
  community.general.copr:
    name: wezfurlong/wezterm-nightly
    state: enabled
  ignore_errors: yes

- name: Install Wezterm
  become: yes
  package: 
    name: "wezterm"
    state: latest
  ignore_errors: yes

- name: Install wezterm on flathub if on aarch64
  community.general.flatpak:
    name: "org.wezfurlong.wezterm"
    state: present
    remote: flathub
  when: ansible_architecture == "aarch64"

# - name: Install Sway (Wayland session)
#   package:
#     name: sway
#     state: present
#   when: lookup('ansible.builtin.env', 'XDG_SESSION_TYPE') == 'wayland'

- name: Install i3 (X11 session)
  become: yes
  package:
    name: i3
    state: present
  # when: lookup('ansible.builtin.env', 'XDG_SESSION_TYPE') == 'x11'
