---
- name: clone my .dotfiles to get ssh keys
  ansible.builtin.git:
    repo: 'https://github.com/DHSYan/.dotfiles.git'
    dest: '/home/tzen/.dotfiles'
    clone: yes
    update: yes

- name: make sure .ssh folder exist
  ansible.builtin.file:
    path: "/home/tzen/.ssh"
    state: directory

- name: Setup my SSH Private
  ansible.builtin.copy:
    dest: "/home/tzen/.ssh/id_rsa"
    content: "{{ lookup('ansible.builtin.file', '/home/tzen/.dotfiles/ssh/keys.secret', decrypt=true) }}"
  become: true

- name: Setup my SSH Public
  ansible.builtin.copy:
    src: "/home/tzen/.dotfiles/ssh/keys.secret.pub"
    dest: "/home/tzen/.ssh/id_rsa.pub"

- name: Symlink my SSH Config 
  ansible.builtin.file:
    src: "/home/tzen/.dotfiles/ssh/config"
    dest: "/home/tzen/.ssh/config"
    state: link


- name: change the github .dotfiles to use SSH
  ansible.builtin.shell:
    cmd: "git remote set-url origin git@github.com:DHSYan/.dotfiles.git"
    chdir: "/home/tzen/.dotfiles"
