---
- name: make sure .ssh folder exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory


- name: Symlink my SSH Config 
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/ssh/config"
    state: link

