---
- name: Update all packages to the latest version
  package:
    name: "*"
    state: latest

# Flatpak and Discord
- name: Install Flatpak
  package:
    name: flatpak
    state: latest

- name: Add the Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flathub Packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flathub_packages }}"

- name: Install flathub Packages that runs on only x86
  community.general.flatpak:
    name: "{{ flathub_packages_x86 }}"
    state: present
    remote: flathub
  when: ansible_architecture == "x86_64"

- name: Install required packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Install required packages when on x86
  package:
    name: "{{ packages_x86 }}"
    state: latest
  when: ansible_architecture == "x86_64"

- name: Install Neovim dependencies
  package:
    name: "{{ neovim_dependencies }}"
    state: latest

- name: Enable Wezterm in Copr
  community.general.copr:
    name: wezfurlong/wezterm-nightly
    state: enabled

- name: Install Wezterm
  package: 
    name: "wezterm"
    state: latest

