---
- name: ensure ZSH is default shell
  become: true
  user:
    # name: "{{ ansible_user_id }}" 
    name: "tzen" 
    state: present
    shell: "/bin/zsh"

- name: create the .zsh_history file in ./config/zsh
  file: 
    path: "{{ lookup('env', 'ZDOTDIR') }}/.zsh_history"
    state: touch

# - name: Check if zap already exist
#   stat: 
#     path: "{{ ansible_env.HOME }}/.local/share/zap"
#   register: zap_exist_stat
#
# - name: Install zap if the regitester didn't exsit
#   shell: "zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) - branch release-v1"
#   when: zap_exist_stat.stat.exists
